version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: .
    network_mode: host
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=contacts

  postgres:
    image: postgres:14
    network_mode: host
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: contacts
